apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "hygieia-api", "namespace": "", "kind": "DeploymentConfig"}]'
    name: hygieia-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/tienhngnguyen/Hygieia-master.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic